# ~/.zshenv: Environment variables for zsh.

### Secrets

# Load secrets from a separate file (untracked)
if [ -f ~/.zshenv.secrets ]; then
  source ~/.zshenv.secrets
fi

# Enable full color support in terminal
export COLORTERM=truecolor

# Default editor: VS Code, Vim
export EDITOR=vim
if command -v code >/dev/null 2>&1; then
    export EDITOR=code
else
    export EDITOR=vim
fi

# Populate PATH
export PATH="/opt/homebrew/bin:${HOME}/.local/bin:${PATH}"
[ -d "${HOME}/.cargo/bin" ] && export PATH="${HOME}/.cargo/bin:${PATH}"

# Keep more history
export HISTSIZE=100_000
export SAVEHIST=100_000
