modmap:
  - name: CapsLock as Left Control
    remap:
      CapsLock: Ctrl_L
  - name: Shift_L as Control+Backslash in Emacs (XWayland)
    application:
      only: Emacs
    remap:
      Shift_L:
        alone: F16
        alone_timeout_millis: 10000
        held: Shift_L
  - name: Shift_L as Control+Backslash in Emacs (Pure GTK on Wayland)
    application:
      only: emacs
    remap:
      Shift_L:
        alone: F16
        alone_timeout_millis: 10000
        held: Shift_L
