#+startup: showeverything
#+html: <div align="center">

* Dotfiles

My collection of text-based files for configuration or other purposes.

#+html: </div>

** List of Files

*** AutoHotkey

AutoHotkey scripts for Windows.  Compile them to exe files and add them to auto start.

- UltimateKEYS-legacy/ :: [[https://github.com/pieter-degroote][Pieter Degroote]]'s UltimateKEYS-legacy keyboard layout, licensed under GPL-3.0.  It's the 2021-07-17 release, and only those AutoHotkey-related files are included.
- emacs-rime-lshift.ahk :: My own AutoHotkey script, which maps the left Shift key to =C-\= (Control+Backslash) in Emacs.

*** Rime

Configuration file of Rime input method.

Install them with ~install.ps1~ on Windows, or ~install.sh~ on Linux.

*** SwitchyOmega

Backup file for SwitchyOmega, a browser addon for switching proxies.

*** Unix

Unix configuration files.  Install them with ~install.sh~ on a GNU/Linux machine.

- fcitx/ :: Fcitx 5 configurations.  This includes themes from [[https://github.com/thep0y/fcitx5-themes][this GitHub repo]].
- xremap/ :: Xremap configurations.
- gnome-dconf/ :: GNOME settings about windows and workspaces.
- dot-bashrc :: Bash configuration.
- dot-bash_profile :: Bash user profile.
- gitconfig :: Git configuration.
- fonts.conf :: Fontconfig configuration.

*** LinuxScripts

A set of scripts to configure Linux.

- cfw.sh :: Wrapper script of Clash-for-windows.  Once Clash-for-windows is installed in ~$HOME/Applications/Clash-for-windows~, add this to Startup Applications like ~sh path/to/cfw.sh~.

*** WindowsScripts

A set of scripts to configure Windows.

- disable-ctrl-space.reg :: Disable the Ctrl+Space shortcut, so that I can use it in Emacs.
- start-vcxsrv.bat :: Launch VcXsrv, a X11 server on Windows.  Add this to startup if you want to use X on WSL.
- wsl1-emacs.bat :: Launch graphical Emacs in WSL 1.
- wsl2-emacs.bat :: Launch graphical Emacs in WSL 2.
