# ~/.zshenv: Main configuration file for zsh.
#
# Copyright 2025 Eric Zhuo Chen

### Antigen

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Locate or download antigen
ANTIGEN="$HOME/.local/bin/antigen.zsh"
if [ ! -f ${ANTIGEN} ]; then
    mkdir -p ${ANTIGEN:h}
    curl -L git.io/antigen > ${ANTIGEN}
fi
source ${ANTIGEN}

# Install oh-my-zsh plugins
antigen use oh-my-zsh
antigen bundle git
antigen bundle command-not-found

# Install other plugins
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme romkatv/powerlevel10k

# Tell antigen you are done
antigen apply

### Keybindings

bindkey -e

### Aliases

alias ls="ls --color -F"
alias ll="ls --color -lh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [ -f ~/.p10k.zsh ]; then
  source ~/.p10k.zsh
fi
