# Configure font
font_family     MesloLGS NF
font_size       11.0

# Initial window size
remember_window_size    no
initial_window_width    100c
initial_window_height   30c

# Tab bar
tab_bar_style   fade
tab_fade 0.5    1
