# ~/.zshenv: Zsh configuration file.
#
# Copyright 2023 Eric Zhuo Chen

### Antigen

ANTIGEN=/usr/share/zsh/share/antigen.zsh
if [ -f ${ANTIGEN} ]; then
    # Load antigen.
    source ${ANTIGEN}

    # Install oh-my-zsh plugins.
    antigen use oh-my-zsh
    antigen bundle git
    antigen bundle commnad-not-found

    # Install other plugins.
    antigen bundle zsh-users/zsh-autosuggestions
    antigen bundle zsh-users/zsh-completions
    antigen bundle zsh-users/zsh-syntax-highlighting
    antigen theme jackharrisonsherlock/common

    # Tell antigen you are done.
    antigen apply
else
    echo "Install antigen to enable plugins."
fi

### History

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

### Keybindings

bindkey -e

### Aliases

alias ls="ls --color -F"
alias ll="ls --color -lh"

# Local Variables:
# mode: sh
# End:
