# ~/.zshenv: Zsh configuration file.
#
# Copyright 2023 Eric Zhuo Chen

### Antigen

# Install antigen.
source /usr/share/zsh/share/antigen.zsh

# Install oh-my-zsh plugins.
antigen use oh-my-zsh
antigen bundle git
antigen bundle commnad-not-found

# Install other plugins.
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting

# Tell antigen you are done.
antigen apply

### Prompt

# Starship must be installed system-wide.
eval "$(starship init zsh)"

### History

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000

### Keybindings

bindkey -v
typeset -g -A key
bindkey '^?' backward-delete-char
bindkey '^[[5~' up-line-or-history
bindkey '^[[3~' delete-char
bindkey '^[[6~' down-line-or-history
bindkey '^[[A' up-line-or-search
bindkey '^[[D' backward-char
bindkey '^[[B' down-line-or-search
bindkey '^[[C' forward-char
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line

### Aliases

alias ls="ls --color -F"
alias ll="ls --color -lh"

# Local Variables:
# mode: sh
# End:
