# ~/.zshenv: Zsh configuration file.
#
# Copyright 2023 Eric Zhuo Chen

### Powerlevel10k Instant Prompt

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

### Antigen

# Locate or download antigen.
ANTIGEN="$HOME/.local/bin/antigen.zsh"
if [ ! -f ${ANTIGEN} ]; then
    mkdir -p ${ANTIGEN:h}
    curl -L git.io/antigen > ${ANTIGEN}
fi
source ${ANTIGEN}

# Install oh-my-zsh plugins.
antigen use oh-my-zsh
antigen bundle git
antigen bundle commnad-not-found

# Install other plugins.
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme romkatv/powerlevel10k

# Tell antigen you are done.
antigen apply

### History

HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000

### Keybindings

bindkey -e

### Aliases

alias ls="ls --color -F"
alias ll="ls --color -lh"

### Home Manager Setup

if [[ -f "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh" ]]; then
    source "$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh"
fi

### Emacs Related

if command -v emacs &> /dev/null; then
    alias ec='emacsclient -c'
    alias ecnw='emacsclient -nw'
    alias enw='emacs -nw'
    alias vim='emacsclient -nw'
    export EDITOR='emacs -nw'
fi

# Setup Direnv

if command -v direnv &> /dev/null; then
    eval "$(direnv hook zsh)"
fi

### Vterm Integration

# Code and comments below are copied from commit 94e2b0b of the emacs-libvterm
# repo.

# Some of the most useful features in emacs-libvterm require shell-side
# configurations. The main goal of these additional functions is to enable the
# shell to send information to `vterm` via properly escaped sequences. A
# function that helps in this task, `vterm_printf`, is defined below.

function vterm_printf(){
    if [ -n "$TMUX" ] && ([ "${TERM%%-*}" = "tmux" ] || [ "${TERM%%-*}" = "screen" ] ); then
        # Tell tmux to pass the escape sequences through
        printf "\ePtmux;\e\e]%s\007\e\\" "$1"
    elif [ "${TERM%%-*}" = "screen" ]; then
        # GNU screen (screen, screen-256color, screen-256color-bce)
        printf "\eP\e]%s\007\e\\" "$1"
    else
        printf "\e]%s\e\\" "$1"
    fi
}

# Completely clear the buffer. With this, everything that is not on screen
# is erased.
if [[ "$INSIDE_EMACS" = 'vterm' ]]; then
    alias clear='vterm_printf "51;Evterm-clear-scrollback";tput clear'
fi

# With vterm_cmd you can execute Emacs commands directly from the shell.
# For example, vterm_cmd message "HI" will print "HI".
# To enable new commands, you have to customize Emacs's variable
# vterm-eval-cmds.
vterm_cmd() {
    local vterm_elisp
    vterm_elisp=""
    while [ $# -gt 0 ]; do
        vterm_elisp="$vterm_elisp""$(printf '"%s" ' "$(printf "%s" "$1" | sed -e 's|\\|\\\\|g' -e 's|"|\\"|g')")"
        shift
    done
    vterm_printf "51;E$vterm_elisp"
}

# This is to change the title of the buffer based on information provided by the
# shell. See, http://tldp.org/HOWTO/Xterm-Title-4.html, for the meaning of the
# various symbols.
autoload -U add-zsh-hook
add-zsh-hook -Uz chpwd (){ print -Pn "\e]2;%m:%2~\a" }

# Sync directory and host in the shell with Emacs's current directory.
# You may need to manually specify the hostname instead of $(hostname) in case
# $(hostname) does not return the correct string to connect to the server.
#
# The escape sequence "51;A" has also the role of identifying the end of the
# prompt
vterm_prompt_end() {
    vterm_printf "51;A$(whoami)@$(hostname):$(pwd)"
}
setopt PROMPT_SUBST
PROMPT=$PROMPT'%{$(vterm_prompt_end)%}'

### Activate Powerlevel10k

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Local Variables:
# mode: sh
# End:
