#!/bin/bash

# Wait until the Emacs service becomes active, then run Emacs client.

# Run Emacs in a new session and log its output.
setsid emacs 2>&1 | logger -t emacs -i &

# Local Variables:
# mode: sh
# End:
