services:
  # Caddy 反向代理
  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./subconv/srv:/srv/subconv
      - ./mirror/srv:/srv/mirror
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: