services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:10
    container_name: forgejo
    restart: unless-stopped
    environment:
      - FORGEJO__database__DB_TYPE=sqlite3
      - FORGEJO__server__DOMAIN=${FORGEJO_DOMAIN}
      - FORGEJO__server__ROOT_URL=http://${FORGEJO_DOMAIN}/
      - FORGEJO__server__SSH_DOMAIN=${FORGEJO_DOMAIN}
    ports:
      - "3000:3000"
      - "2222:22"
    volumes:
      - ${FORGEJO_DATA:-./data}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
